-- MySQL Script generated by MySQL Workbench
-- Sat Oct 29 22:48:36 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema RMS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RMS` DEFAULT CHARACTER SET utf8 ;
USE `RMS` ;

-- -----------------------------------------------------
-- Table `RMS`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RMS`.`Teacher` (
  `idTeacher` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(45) NOT NULL,
  `passWord` VARCHAR(45) NOT NULL,
  `birthday` DATE NULL DEFAULT '1970-07-01',
  `educationBackground` VARCHAR(45) NULL,
  `college` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `ID` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `gender` TINYINT(1) NOT NULL,
  `workPlace` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL,
  `avatarUrl` VARCHAR(45) NULL,
  `param1` VARCHAR(45) NULL,
  `param2` VARCHAR(45) NULL,
  PRIMARY KEY (`idTeacher`),
  UNIQUE INDEX `userName_UNIQUE` (`account` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RMS`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RMS`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(45) NOT NULL,
  `passWord` VARCHAR(45) NOT NULL,
  `param1` VARCHAR(45) NULL,
  `param2` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `adminName_UNIQUE` (`account` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RMS`.`Paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RMS`.`Paper` (
  `idPaper` INT NOT NULL AUTO_INCREMENT,
  `idTeacher` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `writer` VARCHAR(45) NOT NULL,
  `publishDate` DATE NOT NULL,
  `publishPlace` VARCHAR(45) NOT NULL,
  `keyWord` VARCHAR(45) NOT NULL,
  `abstractText` LONGTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `checkStatus` TINYINT(1) NOT NULL DEFAULT 0,
  `param1` VARCHAR(45) NULL,
  `param2` VARCHAR(45) NULL,
  PRIMARY KEY (`idPaper`),
  INDEX `fk_Paper_Teacher_idx` (`idTeacher` ASC),
  CONSTRAINT `fk_Paper_Teacher`
    FOREIGN KEY (`idTeacher`)
    REFERENCES `RMS`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RMS`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RMS`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `idTeacher` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `source` VARCHAR(45) NOT NULL,
  `projectTime` DATE NOT NULL,
  `master` VARCHAR(45) NOT NULL,
  `funds` DECIMAL(20,2) NOT NULL,
  `publishTime` DATE NOT NULL,
  `introduction` LONGTEXT NOT NULL,
  `checkStatus` TINYINT(1) NOT NULL DEFAULT 0,
  `param1` VARCHAR(45) NULL,
  `param2` VARCHAR(45) NULL,
  PRIMARY KEY (`idProject`),
  UNIQUE INDEX `idProject_UNIQUE` (`idProject` ASC),
  INDEX `fk_Project_Teacher1_idx` (`idTeacher` ASC),
  CONSTRAINT `fk_Project_Teacher1`
    FOREIGN KEY (`idTeacher`)
    REFERENCES `RMS`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
